"""add Group.short_name

Revision ID: 23303b7774ef
Revises: 1dc093243ade
Create Date: 2012-12-17 22:26:02.801995

"""

# revision identifiers, used by Alembic.
revision = '23303b7774ef'
down_revision = '1dc093243ade'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('short_name', sa.Unicode(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'short_name')
    ### end Alembic commands ###
